config/routes.rb
Rails.application.routes.draw do
  # Root route pointing to the login menu
  root 'videos#sponsor_intro'

  # Routes for user sign-up, account management, etc.
  resources :users, only: [:new, :create, :show, :edit, :update, :destroy] do
    resources :achievements, only: [:index]
  end

  # Routes for payment processing system
  resources :charges, only: [:create]

  # Custom route for user sign-up
  get 'signup', to: 'users#new', as: :signup

  # Session management routes
  get 'login', to: 'sessions#new', as: :login
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy', as: :logout

  get 'sessions/login_menu', to: 'sessions#login_menu', as: :login_menu

  # Session-related screens

  # Routes for screens after login
  get 'welcome_screen', to: 'sessions#welcome_screen', as: 'welcome_screen'
  get 'main_game_screen', to: 'sessions#main_game_screen', as: 'main_game_screen'
  get 'welcome_settings', to: 'sessions#welcome_settings', as: 'welcome_settings'
  # routes.rb
  resources :servers, only: [:index, :create, :show, :destroy] do
    resources :messages, only: [:create]
    resources :players, only: [] do
      member do
        patch :update_position

        patch :collect_gold
        get :generate_story

        get :ping, to: 'players#ping_players', as: 'ping_players'

      end
    end

    member do
      post :add_user
      get :game_view
      get :grid
      post :send_chat_message
      post :ping_players, to: 'players#ping_players'
    end
  end


  post '/add_user_custom', to: 'servers#add_user_custom', as: :add_user_custom

  get 'user_profile', to: 'sessions#user_profile', as: 'user_profile'
  # config/routes.rb
  #For updating the profile picture
  post '/update_profile_picture', to: 'users#update_profile_picture'
  get 'shard_purchase', to: 'sessions#shard_purchase', as: 'shard_purchase'

  # A route that is used to go to the start screen
  get "videos/start_screen", to: 'videos#start_screen', as: 'start_screen'

  # Route for the sponsor intro video (view, not the file itself)
  get 'videos/sponsor_intro', to: 'videos#sponsor_intro', as: 'sponsor_intro'

  # Route for the game intro video (view, not the file itself)
  get 'videos/game_intro', to: 'videos#game_intro', as: 'game_intro'

  # Route to render the login page after videos are watched
  get 'videos/end_intro', to: 'videos#end_intro', as: 'end_intro'

  resources :storefront, only: [:index] do
    collection do
      post 'purchase_item'
      get 'ships'
      get 'modules'
      get 'crew'
      get 'consumables'
      get 'store_menu'
      post 'update_gold'
    end
  end

  resources :players, only: [] do
    member do
      get 'inventory', to: 'players#inventory' # Add route for the inventory view
    end
    resources :player_items, only: [:index, :create, :update], shallow: true
  end



  patch 'toggle_theme', to: 'sessions#toggle_theme', as: :toggle_theme

  mount ActionCable.server => '/cable'
  post 'convert', to: 'conversions#convert'



  # Route for chat
  post 'chat', to: 'chats#create'



  get 'convert_to_usd', to: 'conversions#convert_to_usd'


  post 'update_session_profile_picture', to: 'sessions#update_session_profile_picture'

  post 'update_session_profile_picture', to: 'sessions#update_session_profile_picture'



end

app/controllers/charges_controller.rb
require 'stripe'
class ChargesController < ApplicationController
  rescue_from Stripe::CardError, Stripe::InvalidRequestError, with: :catch_exception
  before_action :set_params

  def create
    if flash[:alert].present?
      redirect_back fallback_location: 'shard_purchase'
      return
    end

    if @currency == 'JPY'
      amount_cents = (@amount).to_i
    else
      amount_cents = (@amount * 100).to_i
    end

    # Source: 'tok_visa' is a token provided by the stripe API for testing purposes
    charge = Stripe::Charge.create(amount: (amount_cents), source: 'tok_visa', currency: @currency)
    #flash[:notice] = charge[:paid] == true ? success_message(charge) : failure_message

    if charge.paid
      current_user.shards ||= 0
      current_user.shards += @shards

      if current_user.save
        flash[:notice] = success_message(charge)
      else
        flash[:alert] = "Payment succeeded, but we couldn't update your shard balance. Please contact support."
      end
    else
      flash[:alert] = failure_message
    end
    redirect_back fallback_location: 'main_game_screen'
  end

  private

  #set_params works to set those values, shown by errors provided by the Stripe API
  def set_params
    @amount = params[:amount]&.to_f || 0
    @currency = params[:currency] || ''
    @converted_amount = params[:hidden_converted_amount]&.to_f || 0
    @card_number = params[:card_number] || ''
    @card_month = params[:month] || ''
    @card_year = params[:year] || ''
    @cvc = params[:cvc] || ''

    flash[:alert] ||= []

    validate_amount
    validate_currency_existence
    validate_currency
    validate_card_number
    validate_card_expiration
    validate_cvc

    flash[:alert] = flash[:alert].join(' ') if flash[:alert].any?

    if(@currency == 'USD')
      @shards = (@amount / 0.75).floor
    else
      @shards = (@converted_amount / 0.75).floor
    end
  end

  def validate_amount
    flash[:alert] << "| Amount must be greater than 0 |" if @amount <= 0
  end

  def validate_currency_existence
    if @currency == ''
      flash[:alert] <<"| Select a Currency |"
    end
  end

  def validate_currency
    if @currency != 'USD' && @currency != ''
      if @converted_amount <= 0
        flash[:alert] << "| Converted Amount must be calculated for non-USD currencies |"
      end
    end
  end

  def validate_card_number
    flash[:alert] << "| Credit card number must be 16 digits |" if @card_number.length != 16
  end

  def validate_card_expiration
    if @card_year.to_i < Date.today.year % 100 || (@card_year.to_i == Date.today.year % 100 && @card_month.to_i < Date.today.month)
      flash[:alert] << "| Card is expired |"
    end
  end

  def validate_cvc
    flash[:alert] << "| CVC must be a 3-digit number |" if @cvc.length != 3
  end




  def stripe_token
    Stripe::Token.create(card: { number: @card_number, exp_month: @card_month, exp_year: @card_year, cvc: @cvc })
  end

  def catch_exception(exception)
    flash[:alert] = exception.message
    redirect_back fallback_location: 'shard_purchase'
  end

  def success_message(charge)
    "Your payment for #{@shards} has been successfully processed and added to your new total #{current_user.shards} shards.
     You can take your receipt from here: #{charge[:receipt_url]}"
  end

  def failure_message
    "We are sorry. We are unable to proceed with your request. Please try again later."
  end
end

app/views/charges/shard_purchase.html.haml
= form_with url: charges_path, id: 'currency-form' do |f|
  .card-header.py-3.px-4.mb-3.bg-space-station
    %strong Credit Card
    %small.d-block.mt-1.text-muted Please enter your card details below

  .card-body.px-4.py-4.form-space-station
    .form-group.mb-4
      %label{for: "currency"} Select Currency
      = select_tag :currency, options_for_select([["USD", "USD"], ["EUR", "EUR"], ["GBP", "GBP"], ["JPY", "JPY"], ["CAD", "CAD"]]), { prompt: "Choose Currency", class: 'form-control input-space', id: 'currency' }

    .form-group.mb-4
      %label{for: "amount"} Amount
      = f.text_field :amount, class: 'form-control input-space', id: 'amount', placeholder: 'Enter amount'

    .form-group.mb-4
      %label{for: "converted_amount"} Converted Amount (in USD)
      = text_field_tag :converted_amount, '', class: 'form-control input-space', id: 'converted_amount', disabled: true
      = hidden_field_tag :hidden_converted_amount, '', id: 'hidden_converted_amount'

    .form-group.mb-4
      %label{for: "shards"} Shards You Will Obtain
      = text_field_tag :shards, '', class: 'form-control input-space', id: 'shards', disabled: true

    .form-group.mb-4
      = button_tag 'Convert to USD', type: 'button', class: 'btn btn-info btn-sm space-btn', id: 'convert-button'

    .form-group.mb-4
      %label{for: "ccnumber"} Credit Card Number
      = f.text_field :card_number, class: 'form-control input-space', id: 'cardNumber', placeholder: '0000 0000 0000 0000'

    .form-row
      .col-6.form-group.mb-4
        %label{for: "ccmonth"} Expiry Month
        = f.text_field :month, class: 'form-control input-space', id: 'ccmonth', placeholder: 'MM'

      .col-6.form-group.mb-4
        %label{for: "ccyear"} Expiry Year
        = f.text_field :year, class: 'form-control input-space', id: 'ccyear', placeholder: 'YY'

    .form-group.mb-4
      %label{for: "cvv"} CVV/CVC
      = f.text_field :cvc, class: 'form-control input-space', id: 'cvv', placeholder: '123'

      .card-footer.mt-4.d-flex.justify-content-between.align-items-center
        = link_to session[:return_to] || main_game_screen_path, class: 'btn btn-secondary btn-sm space-btn' do
          %i.mdi.mdi-arrow-left
          = " Back to Game"

    = link_to shard_purchase_path, class: 'btn btn-danger btn-sm space-btn' do
      %i.mdi.mdi-lock-reset
      = " Reset"

    = button_to charges_path, class: 'btn btn-success btn-sm space-btn float-right' do
      %i.mdi.mdi-gamepad-circle
      = " Continue"
- if flash[:notice]
  .alert.alert-success= flash.now[:notice]
- if flash[:alert]
  .alert.alert-danger= flash[:alert]

:javascript
  document.addEventListener("DOMContentLoaded", () => {
    const convertButton = document.getElementById('convert-button');
    const currencyField = document.getElementById('currency');
    const amountField = document.getElementById('amount');
    const convertedField = document.getElementById('converted_amount')
    const hiddenConvertedField = document.getElementById('hidden_converted_amount');
    const shardsField = document.getElementById('shards');


    convertButton.addEventListener('click', () => {
      const currency = currencyField.value;
      const amount = amountField.value;

      if (!currency || !amount || amount <= 0) {
        alert("Please select a currency and enter a valid amount.");
        return;
      }

      fetch(`/convert_to_usd?currency=${currency}&amount=${amount}`, {
        method: 'GET',
        headers: { 'Accept': 'application/json' }
      })
      .then(response => response.json())
      .then(data => {
        if (data.converted_amount) {
          convertedField.value = data.converted_amount;
          hiddenConvertedField.value = data.converted_amount;

          const shards = Math.floor(data.converted_amount / 0.75);
          shardsField.value = shards;
        } else {
          alert(data.error || "An error occurred during conversion.");
        }
      })
      .catch(error => console.error("Error:", error));
    });
  });